CREATE TABLE IF NOT EXISTS profile (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    full_name VARCHAR(64) NOT NULL,
    title VARCHAR(64) NOT NULL,
    avatar_url VARCHAR(255) NOT NULL,
    bio VARCHAR(1000) NOT NULL,
    daily_life VARCHAR(1000) NOT NULL,
    skills VARCHAR(500) NOT NULL,
    hobbies VARCHAR(500) NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
